---

dependencies: []

galaxy_info:
  author: klen
  company: Stouts
  description: Manage timezone
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: RedHat
    versions:
    - all
  - name: CentOS
    versions:
    - all
  categories:
  - system
